### PR TITLE
dynamic properties

### PR DESCRIPTION
**Pull request by pimvdnoll**
i'm preparing a generic module which uses this widget, but need some dynamic props

### CODE REVIEW

**Comment by pimvdnoll** [comment]
Hey Bailey can you  merge this one? thnx!

**Comment by simo101** [comment]
Merged Pim. I have taken over the repository now.

**Comment by simo101** [comment]
Taking a look at this again Pim and there is a few things that could be improved. I understand that you want to make this dynamic, but by doing so you are just passing a string, which could result in users submitting wrong values making the widget crash. Also you might not always want this to be dynamic. It would be better if it was in two seperate widgets, one that requires context and one that doesn't. So yours plus the older version. What do you think? If so I can revert this merge.

**Comment by pimvdnoll** [comment]
Hi Simon, thanks for the response.The widget is still working if you pass wrong parameters however it's fine with me if we deliver 2 widgets. Personally I think the widget is much more useful if you can trigger it from anywhere so I made a little free module and submitted it to the Mx appstore (it includes the widget with my code changes). Check my blog about it: http://www.appronto.nl/over-appronto/blog/great-feedback-notifications-in-your-app

**Comment by simo101** [comment]
I will keep it merged for now and we can look at combining both dynamic and not. When i get time ill pick this up and use your new approach but with non dynamic values to.

**Pull request merged**
